version: '3.1'

services:
  db:
    image: mongo:4.0.4
    restart: always
    ports:
      - 27017-27019:27017-27019

  application:
    image: agile_is_the_new_orange:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/springboot-docker-compose-app
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      BOARD_STORE: mongodb://db:27017/agile_is_the_new_orange