spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/agile_is_the_new_orage

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,prometheus